Repository kuzzleio/sdk-cpp, pull requests merged in 2018-11, with the labels that each got.

#19 [fix] Make QueryOptions in adminExists optionnal
  include/server.hpp
Labels: changelog:bug-fixes

#20 [fix] Add sdk-c/build/kuzzle.h to archive
  Makefile
Labels: changelog:exclude

#21 Fix wrapping of options and room options
  CONTRIBUTING.md
  Makefile
  include/kuzzle.hpp
  include/realtime.hpp
  src/auth.cpp
  src/default_constructors.cpp
  src/kuzzle.cpp
  src/realtime.cpp
  test/features/step_definitions/collection-steps.cpp
  test/features/step_definitions/document-steps.cpp
  test/features/step_definitions/kuzzle_utils.cpp
  test/features/step_definitions/realtime-steps.cpp
Labels: changelog:bug-fixes, do not merge

#26 [refactor] rename bridges
  src/kuzzle.cpp
Labels: changelog:enhancements

#29 Fix missing include in package
  .gitignore
  Makefile
Labels: changelog:bug-fixes

#33 remove specificationsearchresult
  include/internal/collection.hpp
  include/internal/search_result.hpp
  src/collection.cpp
  src/specification_search_result.cpp
Labels: changelog:exclude
