Repository kuzzleio/sdk-cpp, pull requests merged in 2018-10, with the labels that each got.

#8 Fix Makefile for Android
  Makefile
Labels: blocked, changelog:bug-fixes

#11 KZL-547 - Update validateSpecifications signature to take index and collection
  include/collection.hpp
  src/collection.cpp
  test/features/step_definitions/collection-steps.cpp
Labels: changelog:enhancements

#10 Add script to align submodule on branch
  CONTRIBUTING.md
  align-submodules.sh
Labels: changelog:enhancements

#16 Fix realtime count arguments
  .travis.yml
  CONTRIBUTING.md
  Makefile
  include/realtime.hpp
  src/realtime.cpp
Labels: changelog:enhancements, do not merge
